[project]
name = "rjones-lab-invasion-assay"
version = "0.1.0"
description = "Pipeline to count nuclei in a cell invasion assay"
readme = "README.md"
requires-python = ">=3.13"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

dependencies = [
    "numpy",
    "scikit-image",
    "matplotlib",
    "tifffile",
    "bioio>=3.5.0",
    "bioio-czi>=2.9.0",
    "oic-toolkit",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
]

[build-system]
requires = ["uv_build>=0.11.26,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "shared"
module-root = ""

[tool.uv.sources]
oic-toolkit = { path = "../../Toolboxes/oic-toolkit", editable = true }
